before_script:
- git config --global user.name 'Nico Taing via Travis CI'
- git config --global user.email 'nico.taing@gmail.com'
- sed -i'' "s~git@github.com:nicotaing/chloepark.git~https://${GH_TOKEN}:x-oauth-basic@github.com/nicotaing/chloepark.git~"
  _config.yml
script:
- hexo deploy --silent
env:
  global:
    secure: Rr6Fg1O7x9x4du34finh+o9+diHmCEtkqS+IwcxK8ygarKFMRas/CDGh4KxfQ2EeNAkHuLj8u73YJrKwLjfDltQfw6sCAcvNsbZuDtoFtIFT8NKAIA3ucc7uZYFVNTy2kv9PujZIk1T4cCtmfDBOYRWk4qp8moDzlcHbNzfahzrcrPpDci3ZsV/7PumE/VJV3WcA1xhJH2u7MUuO9DZjq8PSfH4cm5eOk5zRpRt0rWPAaPb0YF3HtZ8B3FWMMCHonjntcmwsuzAnam9CK9oym1mpKX+4DFUojoniPAcYV7E0sQCEwhxkdI/+dm7Rdi2DrwL1a+1Ao3xkmyhpsFr/I5Mp6O2h85cUeJ1v9zrVj3sGDGQO9LGghALVCvfoNNnzgMMiAP+fu2QjoijJv7h860bhQlWTeyKZvBAF18MD80JlPDnUmeG4ee8Fw8I/8GzKyWP9HrqH0FHGbOgFMvt2QQuAsXxY1r9GZTjMdIcnzfL3rj/8rxM9litwaAjrgGaCDD6B+VhLaHayCD7rYNJZRVCiZ7zsxNelm8MzbgOpiO7R2BYhWTCHLMjLJl7Ypce9MzpJNC7NrLq/HNyR0oCIBBNtvMlZ09dE4ZzdEFydY3KRDmhTTPrZsaYSBgdApGp2UUQaY5SHvS8O1ak66GmO7lEJmeiZjdfv70ybGq1jDuM=
