language: node_js
node_js:
- '4.2'
before_script:
- git config --global user.name 'Nico Taing via Travis CI'
- git config --global user.email 'nico.taing@gmail.com'
- sed -i'' "s~git@github.com:nicotaing/chloepark.git~https://${GH_TOKEN}:x-oauth-basic@github.com/nicotaing/chloepark.git~"
  _config.yml
install:
- npm install
script:
- hexo deploy --silent
env:
  global:
  - secure: YbPzrA5gYp1y6ntw2IdxYVtomjthlNjUyZTl5DrZt/PEptCuWngszGBGx331nhCJsRMun/OOUIZB/o2uDcJu/JY98NMrjJZhbd9FI4/9/f3Kpq9NDg1NNIvmfaA7OA8gpGbIz0K/7nTPgsFj9Vf2qX+dwwphlF5KLYPhXga4zmX4Lhk8Zv87yY38ZlFd9Revk6dpeb8pVp3r34HAEryaxrEa6sToP7iKoPmCoVfU1UniSw+5oK7AkZbyugvEi9Xd0/rhpas8x1uyOYQY2+gdSIamAYnJZQXfTF3GRSqLDRDvORFeIr11xDfyY3LWP9MS0scGUP360AsAC57tp+y+44LtkoK4nl5frl8Snw5XFs1hqgfy2bb/8L28K2nYIg/8GJDi1H2F6ZQBNPdP32L9/ao2nBKTW/3SZ27GJCDwnK771iEFjVaHvsV8SUKTiyIiubyfT+wGpvg2SuAEpSGTXON0HM2r2lUIfO3lvsXeYg2RoBOIZMUIGXsIYR4GJyps7a2yQ6MRldMeHAVMa86rOkR6428eARa4meh7ag6Hyd43VWnweHz6bUUyoZfnY+8fjHjT/uZIaxTdR9NgIZRjSLUJv19euK/5DFOzhHYxhYXEVNZed5mvkbdSlh6/c9AdZN79kFSbQgM/DcXegjUBflsktGQFmtkQOAhD9ZLbSA4=
